apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: toharikrdemolatest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: toharikrdemolatest 
    spec:
      containers:
        - name: toharikrdemolatest 
          image: devopsazure66containerregistry.azurecr.io/toharikrdemolatest
          ports:
          - containerPort: 80